// 100+ Engaging Zomato/Swiggy style notifications for workouts

export const WORKOUT_NOTIFICATIONS = [
    { title: '🍔 Your muscles are starving!', body: 'Delivery: 1x heavy workout coming right up! Open the app to get started.' },
    { title: '🔥 It is getting cold in here...', body: 'Time to turn up the heat! Your workout is ready for you.' },
    { title: '🚨 Code Red! Gym separation anxiety detected.', body: 'Prescription: 60 minutes of lifting heavy things.' },
    { title: '🚚 Special Delivery: Gains!', body: 'Sign here with sweat. Let’s crush today’s session.' },
    { title: '🍕 Craving a slice of success?', body: 'The oven is hot! Get to the gym and bake those gains.' },
    { title: '👀 We saw you looking at the couch.', body: 'Don’t do it! Your workout plan is calling your name.' },
    { title: '⚡ Battery low?', body: 'Exercising actually creates energy. Plug into your workout now!' },
    { title: '😤 "I regret that workout."', body: '- Said no one, ever. Let\'s go make you proud!' },
    { title: '🥊 Round 1... FIGHT!', body: 'You vs. yesterday you. Grab your gear and let the battle begin.' },
    { title: '🏆 Your trophy is getting dusty.', body: 'Time to polish it with a new personal record today.' },
    { title: '☕ Skip the espresso.', body: 'A quick warmup is all the caffeine you need right now.' },
    { title: '🚀 Houston, we are clear for liftoff.', body: 'Initiate workout sequence in 3... 2... 1...' },
    { title: '🌶️ Time to get spicy!', body: 'Add some flavor to your day with a solid sweating session.' },
    { title: '🛡️ Armor upgrade available.', body: 'Equip your gym clothes and level up your stats.' },
    { title: '💸 Deposit required.', body: 'The bank of fitness needs a sweat deposit today. Pay up!' },
    { title: '🛑 STOP SCROLLING.', body: 'Start lifting. Your scheduled workout time is here.' },
    { title: '🎵 Cue the Rocky montage music.', body: 'It’s training time. You know what to do.' },
    { title: '🌊 Ride the wave.', body: 'Endorphins are forming offshore. Go catch them at the gym.' },
    { title: '🏗️ Under Construction', body: 'Grab your hard hat (and sneakers). Time to build a better YOU.' },
    { title: '💎 Diamonds are made under pressure.', body: 'So are muscles. Time to embrace the squeeze.' },
    { title: '🌮 Taco \'bout a great time for a workout!', body: 'Earn your post-workout feast.' },
    { title: '🎭 Main character energy required.', body: 'The spotlight is on you. Go crush this episode (workout).' },
    { title: '🌋 Eruption imminent!', body: 'Release the pressure and blow off some steam with today\'s plan.' },
    { title: '🧩 Missing a piece?', body: 'Your day isn\'t complete without this workout. Let\'s finish the puzzle.' },
    { title: '🛒 Your cart is waiting.', body: 'Checkout with your daily gains before they expire!' },
    { title: '🎢 Ready for the ride?', body: 'Keep your hands inside the gym and secure your grip.' },
    { title: '🔮 We foresee greatness.', body: 'But only if you lace up those shoes and get moving right now.' },
    { title: '🎙️ Mic check, 1-2...', body: 'The stage is yours. Give a legendary performance today.' },
    { title: '🕹️ Player 1, press START.', body: 'Your daily quest is ready. Experience points are waiting.' },
    { title: '🌪️ Bring the storm.', body: 'Wreck your workout before it wrecks you!' },
    { title: '🥑 Guac is extra...', body: 'And so is the effort required today. Give it 110%!' },
    { title: '🧲 Feeling a strange pull?', body: 'That’s the iron calling you. Answer the call.' },
    { title: '🔋 Charge up!', body: 'It’s time to plug in and recharge your mind by pushing your body.' },
    { title: '🎫 VIP Access Granted.', body: 'To the House of Gains. Please proceed to the gym floor.' },
    { title: '🍿 Grab your popcorn.', body: 'Because you’re about to put on a show today.' },
    { title: '🔨 Time to drop the hammer.', body: 'Smash your goals and nail every single rep.' },
    { title: '💡 Lightbulb moment!', body: 'Working out is the smartest thing you can do right now.' },
    { title: '🚿 Warning: Sweat expected.', body: 'Pack a towel. Today\'s session is going to be intense.' },
    { title: '🏔️ The summit awaits.', body: 'Start climbing. Every rep takes you one step closer to the top.' },
    { title: '👑 Crown yourself.', body: 'Rule your day by conquering your workout first.' },
    { title: '🍜 Send Noods?', body: 'No, send NUDGES. Get off the phone and get moving!' },
    { title: '🚨 BEEP BEEP BEEP', body: 'This is the gain alarm. Please evacuate the couch immediately.' },
    { title: '🧨 You are dynamite.', body: 'Time to ignite the fuse and explode into today\'s session.' },
    { title: '🩺 Doctor\'s Orders', body: 'Take 1 heavy workout by mouth... wait, no. Just go to the gym.' },
    { title: '🏎️ Start your engines.', body: 'Green light! Accelerate into your fitness routine.' },
    { title: '🏹 Bullseye!', body: 'You’re right on target. Don’t miss today’s scheduled workout.' },
    { title: '🔑 Unlock your potential.', body: 'The key is consistency. Open the app and turn the lock.' },
    { title: '🍝 Spaghetti arms?', body: 'Not for long. Time to carb-load your muscles with some iron.' },
    { title: '⏳ Tick tock, tick tock...', body: 'The perfect time to work out is exactly right now.' },
    { title: '🕶️ Cool story, bro.', body: 'Now let\'s make it cooler by adding a nasty workout to it.' },
    { title: '📡 Signal detected.', body: 'Transmission: "Get to the gym." End transmission.' },
    { title: '🧛‍♂️ Avoid sunlight?', body: 'Stay in the gym cave instead and lift heavy stuff.' },
    { title: '🥞 Stack \'em up!', body: 'Plates or pancakes? Why not both? Earn the pancakes first.' },
    { title: '🦅 Time to fly.', body: 'Spread your wings (lats) and soar through today’s plan.' },
    { title: '🎈 Don\'t let it fly away.', body: 'Your motivation is right here. Grab it and get to work.' },
    { title: '🧠 Big brain move.', body: 'Exercising now means you get to feel smug for the rest of the day.' },
    { title: '🐉 Wake the dragon.', body: 'Unleash the beast inside you for this next hour.' },
    { title: '🍩 Donut give up!', body: 'Sprinkle some hard work into your day.' },
    { title: '🧭 Lost?', body: 'Let us guide you to the weight rack. Open the app for directions.' },
    { title: '🚦 Green light!', body: 'All systems go. Proceed directly to your workout.' },
    { title: '🔥 Caution: Hot surface.', body: 'Because you’re about to set the gym on fire.' },
    { title: '🎸 Time to rock out.', body: 'Tune your guitar (muscles) and play a heavy metal set.' },
    { title: '🍦 Chill out?', body: 'No way. Sweat it out first, then we can talk about ice cream.' },
    { title: '🐾 Unleash the hound.', body: 'Let the animal out. It’s feeding time... for your muscles.' },
    { title: '⏰ Snooze button broken.', body: 'You’re forced to get up and crush your workout. Sorry not sorry.' },
    { title: '📸 Picture perfect.', body: 'You’re one workout closer to that masterpiece physique.' },
    { title: '🚀 Prepare for warp speed.', body: 'Engage hyperdrive on your fitness journey today.' },
    { title: '🍔 Order up!', body: 'One order of sweat, tears, and victory, extra large.' },
    { title: '💡 Bright idea:', body: 'Going to the gym right now. Trust us.' },
    { title: '⚔️ Draw your sword.', body: 'Slay the laziness dragon and rescue the gains.' },
    { title: '🌊 Tsunami warning.', body: 'A massive wave of endorphins is heading your way. Get ready.' },
    { title: '🎭 No acting required.', body: 'Just raw, unedited effort. Action!' },
    { title: '🥇 Gold medal mentality.', body: 'Train like a champion today.' },
    { title: '🧱 Brick by brick.', body: 'Build the foundation of your fitness one day at a time.' },
    { title: '🍳 Sunny side up.', body: 'Start your day right (or finish it strong) with this session.' },
    { title: '🧨 Explosive power.', body: 'Bring the boom to your workout today.' },
    { title: '🍿 The sequel is better.', body: 'Make today\'s workout better than yesterday\'s.' },
    { title: '🩺 Pulse check.', body: 'Let\'s get that heart rate up where it belongs.' },
    { title: '🔑 The secret ingredient is...', body: 'Showing up. And you\'re scheduled to show up right now.' },
    { title: '🏎️ Fast lane only.', body: 'No speed limits on your progress today.' },
    { title: '🌪️ Whirldwind alert.', body: 'Blow through your sets like a force of nature.' },
    { title: '🥪 A sandwich of sweat.', body: 'Layered with effort, topped with accomplishment.' },
    { title: '🧲 Irresistible force.', body: 'You can\'t ignore the call of the workout any longer.' },
    { title: '🔋 100% Charged.', body: 'Time to drain the battery in the most productive way possible.' },
    { title: '🎫 Admit one.', body: 'Ticket to the gain train. All aboard!' },
    { title: '🔨 Break the mold.', body: 'Create a new you by putting in the work today.' },
    { title: '🚿 Clean slate.', body: 'Wash away the stress with a brutal workout session.' },
    { title: '🏔️ Peak performance.', body: 'Aim for the top today. No half measures.' },
    { title: '👑 Royalty arrives.', body: 'Make your grand entrance at the gym.' },
    { title: '🍜 Slurp up the success.', body: 'It tastes better when you\'ve earned it. Go train!' },
    { title: '🚨 Emergency broadcast.', body: 'Immediate workout required to maintain sanity.' },
    { title: '🎯 Dead center.', body: 'Hit your marks today. Perfection is the goal.' },
    { title: '🧠 Mind over matter.', body: 'If your mind tells you no, tell it to shut up. Let\'s go!' },
    { title: '🐉 Fire breathing.', body: 'Bring the heat to the floor today.' },
    { title: '🍩 A hole in your day?', body: 'Fill it with a solid hour of exercise.' },
    { title: '🧭 True north.', body: 'Always point towards progress. Start now.' },
    { title: '🚦 No red lights here.', body: 'Nothing can stop you. Proceed to your workout.' },
    { title: '🎸 Shred it.', body: 'Tear up those muscles so they grow back stronger.' },
    { title: '🍦 Sweet success.', body: 'Only comes after the bitter taste of hard work.' },
    { title: '🐾 Leave your mark.', body: 'Make sure they remember you were there today.' }
];
